QuizManager/Pages/CreateQuiz.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizManager.Pages
{
    public class QuizManagerModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;

        public QuizManagerModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {

        }
    }
}

QuizManager/Pages/CreateQuizInfo.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizManager.Pages
{
    public class CreateQuizInfoModel : PageModel
    {
        public void OnGet()
        {
        }

        
    }
}

QuizManager/Pages/CreateQuizQuestions.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizManager.Pages
{
    public class CreateQuizQuestionsModel : PageModel
    {
        public void OnGet()
        {

        }
        public string GetColours(int colour)
        {
            IndexModel indexModel = new IndexModel();
            return indexModel.GetColours(colour);
        }
    }
}

QuizManager/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace QuizManager.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

QuizManager/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using QuizManager.Scripts.DatabaseScripts;
using System.IO;
using System.Security.Cryptography;
using System.Text;

namespace QuizManager.Pages
{
    public class IndexModel : PageModel
    {

        string _QuizName { get; set; }
        string _QuizNumber { get; set; }
        string _currentQuestion { get; set; }
        string _maxQuestions { get; set; }
        string _IDValue { get; set; }
        string _QuestonsAnswered { get; set; }


        public IActionResult OnGet()
        {
            string path = HttpContext.Request.Path;

            if (path != "/")
            {
                AccessDatabase accessDatabase = new AccessDatabase();
                List<string> userDetails = accessDatabase.ReadUserInfo();
                if (userDetails.Count <= 2)
                {
                    return new RedirectToPageResult("Index");
                }
                if (string.IsNullOrEmpty(userDetails[0]) || string.IsNullOrEmpty(userDetails[1]) || string.IsNullOrEmpty(userDetails[2]))
                {
                    return new RedirectToPageResult("Index");
                }
            }
            else
            {
                AccessDatabase accessDatabase = new AccessDatabase();
                List<string> userDetails = accessDatabase.ReadUserInfo();
                if (!string.IsNullOrEmpty(userDetails[0]) || !string.IsNullOrEmpty(userDetails[1]) || !string.IsNullOrEmpty(userDetails[2]))
                {
                    return new RedirectToPageResult("JoinPage");
                }
            }
             
            path = path.Replace("/", "");
            return new PageResult();
        }

        public string GetColours(int colour)
        {
            FileHandler filehandler = new FileHandler();
            return filehandler.ReadFromColoursFile(colour);
        }

        public IActionResult OnPostQuizInfo()
        {
            string quizName = InvalidCharCheck(Request.Form["QuizName"]);
            string quizType = InvalidCharCheck(Request.Form["QuizType"]);            

            AccessDatabase accessDatabase = new AccessDatabase();
            int joinValue = accessDatabase.AddNewQuizInfoToDatabase(quizName, quizType);

            string joinName = accessDatabase.CreateNewQuestionTable(joinValue);
            int currentQuestion = 1;
            accessDatabase.WriteToCurrentQuiz(quizName, joinName, currentQuestion, currentQuestion, currentQuestion);

            //accessDatabase.SQLTableSetAutoIncrement(joinName);

            return RedirectToPage("CreateQuizQuestions");
        }

        public IActionResult OnPostColourChange()
        {
            string colour1 = Request.Form["colour1"];
            string colour2 = Request.Form["colour2"];
            string colour3 = Request.Form["colour3"];

            FileHandler filehandler = new FileHandler();
            filehandler.WriteColoursToFile(colour1, colour2, colour3);

            return RedirectToPage("Settings");
        }

        public IActionResult OnPostCreateQuizInfoSave()
        {
            string radio = InvalidCharCheck(Request.Form["answerpick"].ToString());
            if (string.IsNullOrEmpty(radio))
            {
                return RedirectToPage("CreateQuizQuestions"); //Add error page
            }
            int answer = Int32.Parse(radio);
            string quesDescription = InvalidCharCheck(Request.Form["QuizQuestion"].ToString());
            string answerdes1 = InvalidCharCheck(Request.Form["QuizAnswer1"].ToString());
            string answerdes2 = InvalidCharCheck(Request.Form["QuizAnswer2"].ToString());
            string answerdes3 = InvalidCharCheck(Request.Form["QuizAnswer3"].ToString());
            string answerdes4 = InvalidCharCheck(Request.Form["QuizAnswer4"].ToString());
            if(string.IsNullOrEmpty(quesDescription) || string.IsNullOrEmpty(answerdes1) || string.IsNullOrEmpty(answerdes2) || string.IsNullOrEmpty(answerdes3) || string.IsNullOrEmpty(answerdes4))
            {
                return RedirectToPage("CreateQuizQuestions"); //Add error page
            }
            if (string.IsNullOrEmpty(_QuizNumber))
            {
                _QuizNumber = GetCurrentQuizNumber();
            }
            if (string.IsNullOrEmpty(_currentQuestion))
            {
                _currentQuestion = GetCurrentQuestionNumber();
            }
            int quizNumber = Int32.Parse(_QuizNumber);
            int currentQuestion = Int32.Parse(_currentQuestion);

            AccessDatabase accessDatabase = new AccessDatabase();
            accessDatabase.UpdateCurrentQuizQuestionTable(quizNumber, currentQuestion, answer, quesDescription,
                                           answerdes1, answerdes2, answerdes3, answerdes4);

            return RedirectToPage("CreateQuizQuestions");
        }

        public IActionResult OnPostCreateQuizInfoSaveAndQuit()
        {
            string radio = InvalidCharCheck(Request.Form["answerpick"].ToString());
            if (string.IsNullOrEmpty(radio))
            {
                return RedirectToPage("CreateQuizQuestions"); //Add error page
            }
            int answer = Int32.Parse(radio);
            string quesDescription = InvalidCharCheck(Request.Form["QuizQuestion"].ToString());
            string answerdes1 = InvalidCharCheck(Request.Form["QuizAnswer1"].ToString());
            string answerdes2 = InvalidCharCheck(Request.Form["QuizAnswer2"].ToString());
            string answerdes3 = InvalidCharCheck(Request.Form["QuizAnswer3"].ToString());
            string answerdes4 = InvalidCharCheck(Request.Form["QuizAnswer4"].ToString());
            if (string.IsNullOrEmpty(quesDescription) || string.IsNullOrEmpty(answerdes1) || string.IsNullOrEmpty(answerdes2) || string.IsNullOrEmpty(answerdes3) || string.IsNullOrEmpty(answerdes4))
            {
                return RedirectToPage("CreateQuizQuestions"); //Add error page
            }
            if (string.IsNullOrEmpty(_QuizNumber))
            {
                _QuizNumber = GetCurrentQuizNumber();
            }
            if (string.IsNullOrEmpty(_currentQuestion))
            {
                _currentQuestion = GetCurrentQuestionNumber();
            }
            int quizNumber = Int32.Parse(_QuizNumber);
            int currentQuestion = Int32.Parse(_currentQuestion);

            AccessDatabase accessDatabase = new AccessDatabase();
            accessDatabase.UpdateCurrentQuizQuestionTable(quizNumber, currentQuestion, answer, quesDescription,
                                           answerdes1, answerdes2, answerdes3, answerdes4);

            return RedirectToPage("CreateQuiz");
        }

        public IActionResult OnPostCreateQuizInfoBack()
        {
            return RedirectToPage("CreateQuiz");
        }

        public IActionResult OnPostAnswerQuizInfoBack()
        {
            return RedirectToPage("JoinPage");
        }

        public IActionResult OnPostAnswerQuizInfoFinish()
        {
            return RedirectToPage("QuizResults");
        }

        public IActionResult OnPostCreateQuizInfoAdd()
        {
            if (string.IsNullOrEmpty(_currentQuestion))
            {
                _currentQuestion = GetCurrentQuestionNumber();
            }
            if (string.IsNullOrEmpty(_maxQuestions))
            {
                _maxQuestions = GetCurrentQuestionMaxQuestion();
            }
            if (string.IsNullOrEmpty(_QuizNumber))
            {
                _QuizNumber = GetCurrentQuestionNumber();
            }
            if (string.IsNullOrEmpty(_QuizName))
            {
                _QuizName = GetCurrentQuizName();
            }
            if (string.IsNullOrEmpty(_IDValue))
            {
                _IDValue = GetCurrentQuestionIDValue();
            }
            int maxQuestions = Int32.Parse(_maxQuestions);
            int currentQuestion = Int32.Parse(_currentQuestion);
            int idValue = Int32.Parse(_IDValue);
            maxQuestions = maxQuestions + 1;
            idValue = idValue + 1;

            AccessDatabase accessDatabase = new AccessDatabase();
            accessDatabase.AddNewQuizQuestionToCurrentQuiz(maxQuestions, _QuizNumber, idValue);

            accessDatabase.WriteToCurrentQuiz(_QuizName, _QuizNumber, currentQuestion, maxQuestions, idValue);

            _maxQuestions = maxQuestions.ToString();

            return RedirectToPage("CreateQuizQuestions");
        }

        public IActionResult OnPostCreateQuizInfoDelete()
        {
            if (string.IsNullOrEmpty(_currentQuestion))
            {
                _currentQuestion = GetCurrentQuestionNumber();
            }
            if (string.IsNullOrEmpty(_QuizNumber))
            {
                _QuizNumber = GetCurrentQuestionNumber();
            }
            if (string.IsNullOrEmpty(_maxQuestions))
            {
                _maxQuestions = GetCurrentQuestionMaxQuestion();
            }
            if (string.IsNullOrEmpty(_QuizName))
            {
                _QuizName = GetCurrentQuizName();
            }
            if (string.IsNullOrEmpty(_IDValue))
            {
                _IDValue = GetCurrentQuestionIDValue();
            }
            int currentQuestion = Int32.Parse(_currentQuestion);
            int maxQuestions = Int32.Parse(_maxQuestions);

            AccessDatabase accessDatabase = new AccessDatabase();
            accessDatabase.QuizQuestionDeleteRow(_QuizNumber, currentQuestion);

            maxQuestions = maxQuestions - 1;

            if (currentQuestion > maxQuestions )
            {
                currentQuestion = maxQuestions;
                _currentQuestion = currentQuestion.ToString();
            }
            
            int idValue = Int32.Parse(_IDValue);

            _maxQuestions = maxQuestions.ToString();

QuizManager/Pages/JoinPage.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizManager.Pages
{
    public class JoinPageModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

QuizManager/Pages/Login.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizManager.Pages.Login
{
    public class LoginModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

QuizManager/Pages/ManageClass.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizManager.Pages
{
    public class ManageClassModel : PageModel
    {
        public void OnGet()
        {
        }
        public string GetColours(int colour)
        {
            FileHandler filehandler = new FileHandler();
            return filehandler.ReadFromColoursFile(colour);
        }
    }
}

QuizManager/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace QuizManager.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
        public string GetColours(int colour)
        {
            FileHandler filehandler = new FileHandler();
            return filehandler.ReadFromColoursFile(colour);
        }
    }
}

QuizManager/Pages/Settings.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.IO;
using System.Text;

namespace QuizManager.Pages
{
    public class SettingsModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

QuizManager/Pages/CreateQuizQuestions.cshtml
@page
@model QuizManager.Pages.IndexModel
@{
    <style>
        .CommentBox{
            width:65%;
            height:80%;
            border:5px solid @Model.GetColours(0);
            position: absolute;
            top: 52%;
            right: 55%;
            -ms-transform: translateY(-50%) translateX(50%);
            transform: translateY(-50%) translateX(50%);
            margin:0 auto;
            background-color:@Model.GetColours(1);
        }
        .CommentBox2{
            width:15%;
            height:80%;
            border:5px solid @Model.GetColours(0);
            position: absolute;
            top: 52%;
            right: 10%;
            -ms-transform: translateY(-50%) translateX(50%);
            transform: translateY(-50%) translateX(50%);
            margin:0 auto;
            background-color:@Model.GetColours(1);
        }
        .TextBoxQuestion{
              top: 28%;
              right: 50%;
              position: absolute;
              -ms-transform: translateY(-50%) translateX(50%);
              transform: translateY(-50%) translateX(50%);
              font-size: 1.8vw;
              /*border:3px solid #000000;*/
              width: 70%;
        }
        .TextBox{
              top: 50%;
              right: 75%;
              position: absolute;
              -ms-transform: translateY(-50%) translateX(50%);
              transform: translateY(-50%) translateX(50%);
              font-size: 1.8vw;
              /*border:3px solid #000000;*/
              width: 30%;
        }
        .TextBox2{
              top: 50%;
              right: 25%;
              position: absolute;
              -ms-transform: translateY(-50%) translateX(50%);
              transform: translateY(-50%) translateX(50%);
              font-size: 1.8vw;
              /*border:3px solid #000000;*/
              width: 30%;
        }
        .TextBox3{
              top: 70%;
              right: 75%;
              position: absolute;
              -ms-transform: translateY(-50%) translateX(50%);
              transform: translateY(-50%) translateX(50%);
              font-size: 1.8vw;
              /*border:3px solid #000000;*/
              width: 30%;
        }
        .TextBox4{
              top: 70%;
              right: 25%;
              position: absolute;
              -ms-transform: translateY(-50%) translateX(50%);
              transform: translateY(-50%) translateX(50%);
              font-size: 1.8vw;
              /*border:3px solid #000000;*/
              width: 30%;
        }
        .Text{
            right: 45%;
            position: absolute;
            font-size: 2vw;
        }
        .Text2{
            font-size: 1.2vw;
        }

        .EnterText{
            top: 38%;
            right: 61%;
            position: absolute;
            -ms-transform: translateY(-50%) translateX(42%);
            transform: translateY(-50%) translateX(42%);
        }
        .JoinButton{
            top: 85%;
            right: 20%;
            position: absolute;
            background-color:#0a8a06;
            margin: 0 auto;
            width: 10%;
            height: 8%;
            font-size: 14px;
            line-height: 1.4;
            text-align: center;
            list-style-type: none;
            list-style-position: outside;
            text-decoration: none;
        }
        .JoinButton:hover{
            background-color:#043b02!important;
            text-decoration: none;
            color: #FFFFFF;
        }
        .SaveExitButton{
            top: 85%;
            right: 45%;
            position: absolute;
            background-color:#0a8a06;
            margin: 0 auto;
            width: 15%;
            height: 8%;
            font-size: 14px;
            line-height: 1.4;
            text-align: center;
            list-style-type: none;
            list-style-position: outside;
            text-decoration: none;
        }
        .SaveExitButton:hover{
            background-color:#043b02!important;
            text-decoration: none;
            color: #FFFFFF;
        }
        .BackButton{
            top: 85%;
            right: 70%;
            position: absolute;
            background-color:#52504d;
            margin: 0 auto;
            width: 10%;
            height: 8%;
            font-size: 14px;
            line-height: 1.4;
            text-align: center;
            list-style-type: none;
            list-style-position: outside;
            text-decoration: none;
        }
        .BackButton:hover{
            background-color:#363533!important;
            text-decoration: none;
            color: #FFFFFF;
        }
        .AddButton{
            top: 80%;
            right: 40%;
            position: absolute;
            background-color:#7d7c7a;
            margin: 0 auto;
            width: 25%;
            height: 10%;
            font-size: 14px;
            line-height: 1.4;
            text-align: center;
            list-style-type: none;
            list-style-position: outside;
            text-decoration: none;
        }
        .AddButton:hover{
            background-color:#52504d!important;
            text-decoration: none;
            color: #FFFFFF;
        }
        .DeleteButton{
            top: 90%;
            right: 40%;
            position: absolute;
            background-color:#ba0606;
            margin: 0 auto;
            width: 25%;
            height: 10%;
            font-size: 14px;
            line-height: 1.4;
            text-align: center;
            list-style-type: none;
            list-style-position: outside;
            text-decoration: none;
        }
        .DeleteButton:hover{
            background-color:#690202!important;
            text-decoration: none;
            color: #FFFFFF;
        }
        .NextButton{
            top: 80%;
            right: 10%;
            position: absolute;
            background-color:#7d7c7a;
            margin: 0 auto;
            width: 25%;
            height: 20%;
            font-size: 14px;
            line-height: 1.4;
            text-align: center;
            list-style-type: none;
            list-style-position: outside;
            text-decoration: none;
        }
        .NextButton:hover{
            background-color:#52504d!important;
            text-decoration: none;
            color: #FFFFFF;
        }
        .PrevButton{
            top: 80%;
            right: 70%;
            position: absolute;
            background-color:#7d7c7a;
            margin: 0 auto;
            width: 25%;
            height: 20%;
            font-size: 14px;
            line-height: 1.4;
            text-align: center;
            list-style-type: none;
            list-style-position: outside;
            text-decoration: none;
        }
        .PrevButton:hover{
            background-color:#52504d!important;
            text-decoration: none;
            color: #FFFFFF;
        }

        .text-under{
            display:block;
            font-size: 1.4vw;  
        }
        .checkbox{
            font-size: 2vw;
        }
    </style>
    <body style="background-color:@Model.GetColours(2);">
            <form class="form-horizontal" method="post">
                <div class="CommentBox">
                    <div class="Text">
                        <b style="text-align:center; font-size:30px; color:black;">@Model.GetCurrentQuizQuestion()</b>
                    </div>
                    <div class="form-group">
                        <div class="TextBoxQuestion" >
                            <input style="border-style:solid; border-color:black; border-width:3px;" class="form-control" id="QuizAnswer1" name="QuizQuestion" value="@Model.GetCurrentQuizAnswerQuestion(2)" >
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="TextBox" >
                            <input style="border-style:solid; border-color:black; border-width:3px;" class="form-control" id="QuizAnswer1" name="QuizAnswer1" value="@Model.GetCurrentQuizAnswerQuestion(3)" >
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="TextBox2" >
                            <input style="border-style:solid; border-color:black; border-width:3px;" class="form-control" id="QuizAnswer2" name="QuizAnswer2" value="@Model.GetCurrentQuizAnswerQuestion(4)" >
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="TextBox3" >
                            <input style="border-style:solid; border-color:black; border-width:3px;" class="form-control" id="QuizAnswer3" name="QuizAnswer3" value="@Model.GetCurrentQuizAnswerQuestion(5)" >
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="TextBox4" >
                            <input style="border-style:solid; border-color:black; border-width:3px;" class="form-control" id="QuizAnswer4" name="QuizAnswer4" value="@Model.GetCurrentQuizAnswerQuestion(6)" >
                        </div>
                    </div>
                    <div class="Text2">
                        <b style="color:black; top: 20%; right: 70%; position: absolute;">Question Name:</b>
                    </div>
                    <div class="Text2">
                        <b style="color:black; top: 42%; right: 80%; position: absolute;">Answer 1:</b>
                    </div>
                    <div class="Text2">
                        <b style="color:black; top: 42%; right: 30%; position: absolute;">Answer 2:</b>
                    </div>
                    <div class="Text2">
                        <b style="color:black; top: 62%; right: 80%; position: absolute;">Answer 3:</b>
                    </div>
                    <div class="Text2">
                        <b style="color:black; top: 62%; right: 30%; position: absolute;">Answer 4:</b>
                    </div>
                    <div class="checkbox">
                        <input type="radio" id="answer1pick" name="answerpick" value="1" checked="@Model.GetCurrentQuizRadioButton(1)" style="top:48.5%; right:90%; position: absolute; width:3%; height:3%;">
                    </div>
                    <div class="checkbox">
                        <input type="radio" id="answer2pick" name="answerpick" value="2" checked="@Model.GetCurrentQuizRadioButton(2)" style="top:48.5%; right:40%; position: absolute; width:3%; height:3%;">
                    </div>
                    <div class="checkbox">
                        <input type="radio" id="answer3pick" name="answerpick" value="3" checked="@Model.GetCurrentQuizRadioButton(3)" style="top:68.5%; right:90%; position: absolute; width:3%; height:3%;">
                    </div>
                    <div class="checkbox">
                        <input type="radio" id="answer4pick" name="answerpick" value="4" checked="@Model.GetCurrentQuizRadioButton(4)" style="top:68.5%; right:40%; position: absolute; width:3%; height:3%;">
                    </div>
                    <button type="Create" asp-page-handler="CreateQuizInfoSave" class="JoinButton text-under">Save</button>
                    <button type="Create" asp-page-handler="CreateQuizInfoBack" class="BackButton text-under">Back</button>
                    <button type="Create" asp-page-handler="CreateQuizInfoSaveAndQuit" class="SaveExitButton text-under">Save & Exit</button>
                </div>
                <div class="CommentBox2">
                    <div class="Text2">
                        <b style="color:black; top: 1%; right: 32.5%; position: absolute;">Questions:</b>
                    </div>
                    <div class="Text2">
                        <b style="color:black; top: 1%; right: 32.5%; position: absolute;">Questions:</b>
                    </div>
                    <div class="Text2">
                        <b style="color:black; top: 50%; right: 20%; position: absolute;">Quiz Join Number:</b>
                    </div>
                    <div class="Text2">
                        <b style="color:black; top: 55%; right: 40%; position: absolute;">@Model.ShowJoinQuizNumber()</b>
                    </div>
                    <div class="Text2">
                        <b style="color:black; top: 60%; right: 2%; position: absolute;">(Remember This Value)</b>
                    </div>
                    <button type="Create" asp-page-handler="CreateQuizInfoAdd" class="AddButton text-under">Add</button>
                    <button type="Create" asp-page-handler="CreateQuizInfoDelete" hidden="@Model.CreateQuizShouldShowDeleteButton()" class="DeleteButton text-under">Del</button>
                    <button type="Create" asp-page-handler="CreateQuizInfoNext" hidden="@Model.CreateQuizShouldShowNextButton()" class="NextButton text-under">Next<br/>></button>
                    <button type="Create" asp-page-handler="CreateQuizInfoPrev" hidden="@Model.CreateQuizShouldShowPrevButton()" class="PrevButton text-under">Prev<br/>&lt;</button>
                </div>
            </form>

    </body>
}

QuizManager/Pages/Login.cshtml
@page
@model QuizManager.Pages.Login.LoginModel
@{
	Layout = "~/Pages/Shared/_LoginLayout.cshtml";
	ViewBag.Title = "Log in";
}

<head>

</head>

QuizManager/Pages/QuizResults.cshtml
@page
@model QuizManager.Pages.IndexModel
@{
}
<style>
.CommentBox{
    width:80%;
    height:80%;
    border:5px solid @Model.GetColours(0);
    position: absolute;
    top: 52%;
    right: 45%;
    -ms-transform: translateY(-50%) translateX(50%);
    transform: translateY(-50%) translateX(50%);
    margin:0 auto;
    background-color:@Model.GetColours(1);
}
.TextBox{
    top: 50%;
    right: 50%;
    position: absolute;
    -ms-transform: translateY(-50%) translateX(50%);
    transform: translateY(-50%) translateX(50%);
    font-size: 1.8vw;
    /*border:3px solid #000000;*/
    width: 50%;
}
.Text{
    right: 45%;
    position: absolute;
    font-size: 2vw;
}
.Text2{
    font-size: 3vw;
}

.EnterText{
    top: 38%;
    right: 61%;
    position: absolute;
    -ms-transform: translateY(-50%) translateX(42%);
    transform: translateY(-50%) translateX(42%);
}
.JoinButton{
    top: 65%;
    right: 48%;
    position: absolute;
    background-color:#0a8a06;
    margin: 0 auto;
    width: 10%;
    height: 15%;
    font-size: 33px;
    line-height: 1.4;
    text-align: center;
    list-style-type: none;
    list-style-position: outside;
    text-decoration: none;
}
.JoinButton:hover{
    background-color:#043b02!important;
    text-decoration: none;
    color: #FFFFFF;
}
.text-under{
    display:block;
    font-size: 1.8vw;  
}
.BackButton{
            top: 85%;
            right: 45%;
            position: absolute;
            background-color:#52504d;
            margin: 0 auto;
            width: 10%;
            height: 8%;
            font-size: 1.8vw;
            line-height: 1.4;
            text-align: center;
            list-style-type: none;
            list-style-position: outside;
            text-decoration: none;
        }
.BackButton:hover{
            background-color:#363533!important;
            text-decoration: none;
            color: #FFFFFF;
}
</style>

<body style="background-color:@Model.GetColours(2);">
    <form class="form-horizontal" method="post">
        <div class="CommentBox">
            <div class="Text">
                <b style="text-align:center; font-size:30px; color:black;">Results:</b><br>
            </div>
            <div class="Text2">
                <b style="color:black; top: 40%; right: 38%; position: absolute;">You Scored:</b>
            </div>
            <div class="Text2">
                <b style="color:black; top: 50%; right: 40%; position: absolute;">@Model.GetJoinQuizResults()</b>
            </div>
            <button type="Create" asp-page-handler="AnswerQuizInfoBack" class="BackButton text-under">Exit</button>
        </div>
    </form>
    

</body>